#!/bin/sh

echo "> Task: detekt"

./gradlew --no-daemon detekt

detektStatus=$?

# return 1 exit code if running checks fails
[ $detektStatus -ne 0 ] && exit 1

echo "> Task: ktfmtFormat"

./gradlew ktfmtFormat

echo "> Task: ktfmtCheck"

./gradlew --no-daemon ktfmtCheck

checkStyleStatus=$?

# return 1 exit code if running checks fails
[ $checkStyleStatus -ne 0 ] && exit 1
exit 0
