name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Generate JaCoCo coverage report
        run: ./gradlew test jacocoTestReport
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: library/build/reports/jacoco/test/html
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: library/build/reports/jacoco/test/jacocoTestReport.csv

